require('config.buffer')
require('config.grep')
require('config.indent')
require('config.lazy')
require('config.line_number')
require('config.lualine')
require('config.mark')
require('config.old_files')
require('config.quickfix')
require('config.terminal')
require('config.window')

